#! /bin/busybox sh

# vim: set filetype=sh:

# Redirect all output and error messages to the system console during boot.
exec >/dev/console 2>&1

# Rescue shell
rescue_shell() {
    echo "Something went wrong. Dropping to a shell."
    exec sh
}

# Mount devtmpfs to find devices.
mount -t devtmpfs none /dev || rescue_shell

# Mount the /proc and /sys filesystems.
mount -t proc none /proc || rescue_shell
mount -t sysfs none /sys || rescue_shell

# Mount the root filesystem.
echo "Mounting root filesystem..."
mount -o ro $(findfs LABEL=myroot) /mnt/root || rescue_shell

# Clean up.
umount /proc
umount /sys
umount /dev

# Switch to rootfs
exec switch_root /mnt/root /sbin/init || rescue_shell
