#! /bin/busybox sh

# vim: set filetype=sh:

# Redirect all output and error messages to the system console during boot.
exec >/dev/console 2>&1

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
